version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/visionbox_apps/age-predict-webapp/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    assignees:
      - "yudataguy"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/visionbox_apps/age-predict-webapp/frontend/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    assignees:
      - "yudataguy"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/visionbox_apps/age-predict-webapp/server/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    assignees:
      - "yudataguy"
