version: '3.3'
services:
  web:
    build: 
      context: ../
      dockerfile: ./server/Dockerfile
    ports:
      - "4000:4000"
  agebox:
    image: "trueface/agebox:latest"
    ports:
      - "9000:8080"
    environment:
        - TOKEN